<?php

namespace Database\Seeders;

use App\Models\Branch;
use App\Models\Doctor;
use App\Models\GalleryCase;
use App\Models\Service;
use Illuminate\Database\Seeder;

/**
 * Demo content for the public results gallery.
 *
 * The images are the abstract placeholder plates in public/gallery-demo
 * (generated by scripts/make_gallery_placeholders.py), NOT photographs. A
 * clinic replaces them with their own consented patient photography — these
 * exist so the page and its comparison slider can be demonstrated without
 * anything on screen pretending to be a real clinical result.
 */
class EvaGalleryDemoSeeder extends Seeder
{
    /**
     * [image key, service slug, title en/ar, summary en/ar, protocol en/ar]
     *
     * Service slugs are the medical-template ones the catalog still uses as
     * keys — see BeautyClinicDataSeeder for the mapping to beauty categories.
     */
    private const CASES = [
        ['laser', 'cardiology',
            'Laser hair removal — underarms', 'إزالة الشعر بالليزر — الإبطين',
            'Six sessions spaced four weeks apart, with a marked reduction in density from the third session.',
            'ست جلسات بفاصل أربعة أسابيع، مع انخفاض ملحوظ في الكثافة من الجلسة الثالثة.',
            '6 sessions · 24 weeks', '٦ جلسات · ٢٤ أسبوعًا'],

        ['acne', 'ent',
            'Active acne programme', 'برنامج علاج حب الشباب',
            'Combined medical and peel protocol for inflammatory acne, reviewed at every visit.',
            'بروتوكول طبي مع جلسات تقشير لحب الشباب الالتهابي، مع مراجعة في كل زيارة.',
            '4 sessions · 12 weeks', '٤ جلسات · ١٢ أسبوعًا'],

        ['glow', 'pediatrics',
            'Glow & rejuvenation course', 'دورة النضارة والتجديد',
            'Hydrating facial course with a brightening peel, timed ahead of a wedding.',
            'دورة عناية مرطّبة مع تقشير للإشراق، بتوقيت يسبق موعد المناسبة.',
            '3 sessions · 6 weeks', '٣ جلسات · ٦ أسابيع'],

        ['filler', 'dentistry',
            'Lip enhancement', 'نضارة وامتلاء الشفاه',
            'A single conservative session, shaped over two appointments two weeks apart.',
            'جلسة واحدة متحفّظة، على موعدين بفاصل أسبوعين.',
            '1 session · 2 reviews', 'جلسة واحدة · مراجعتان'],

        ['pigment', 'dermatology',
            'Melasma & pigmentation', 'الكلف والتصبغات',
            'Four-session pigmentation course with daily home care and strict photoprotection.',
            'دورة من أربع جلسات للتصبغات مع روتين منزلي يومي وحماية دقيقة من الشمس.',
            '4 sessions · 16 weeks', '٤ جلسات · ١٦ أسبوعًا'],

        ['hair', 'gynecology',
            'Hair restoration programme', 'برنامج إعادة إنبات الشعر',
            'Scalp PRP course following a full hair-loss diagnosis and treatment plan.',
            'دورة بلازما لفروة الرأس بعد تشخيص كامل لتساقط الشعر وخطة علاجية.',
            '4 sessions · 16 weeks', '٤ جلسات · ١٦ أسبوعًا'],
    ];

    public function run(): void
    {
        $branch = Branch::query()->orderBy('id')->first();

        if (! $branch) {
            $this->command?->warn('No branches found — skipping gallery demo cases.');

            return;
        }

        $doctors = Doctor::query()->where('branch_id', $branch->id)->where('is_active', true)->get();

        foreach (self::CASES as $i => [$key, $serviceSlug, $titleEn, $titleAr, $sumEn, $sumAr, $protoEn, $protoAr]) {
            $service = Service::query()->where('slug', $serviceSlug)->first();

            GalleryCase::updateOrCreate(
                ['before_image_url' => "/gallery-demo/{$key}-before.svg"],
                [
                    'service_id' => $service?->id,
                    'branch_id' => $branch->id,
                    'doctor_id' => $doctors->get($i % max(1, $doctors->count()))?->id,
                    'title' => ['en' => $titleEn, 'ar' => $titleAr],
                    'summary' => ['en' => $sumEn, 'ar' => $sumAr],
                    'protocol' => ['en' => $protoEn, 'ar' => $protoAr],
                    'after_image_url' => "/gallery-demo/{$key}-after.svg",
                    // Demo rows: the real workflow is reception ticking this only
                    // once a signed consent form is on file.
                    'consent_on_file' => true,
                    'is_published' => true,
                    'sort_order' => $i + 1,
                ],
            );
        }

        $this->command?->info('Seeded '.count(self::CASES).' demo gallery cases (placeholder artwork).');
    }
}
