<?php

namespace App\Http\Controllers\V2;

use App\Http\Controllers\Controller;
use App\Models\Accounting\Account;
use App\Models\Accounting\Expense;
use App\Models\Accounting\Vendor;
use App\Support\ResolvesAccessibleClinics;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Inertia\Inertia;
use Inertia\Response;

/**
 * Expenses — v2 replacement for Filament ExpenseResource.
 * Draft → Posted (post() routes through AccountingService::recordExpense) → Void
 * (reverses the GL entry). Code is auto-generated by the model on save.
 */
class ExpensesController extends Controller
{
    use ResolvesAccessibleClinics;

    protected function authorizeAccess(Request $request): void
    {
        if (! $request->user() || ! $request->user()->can('view_any_accounting_expenses')) {
            abort(403, 'Not authorized to view expenses.');
        }
    }

    protected function canEdit(Request $request): bool
    {
        return (bool) $request->user()?->can('update_accounting_expenses');
    }

    /** Styled .xlsx export of expenses (mirrors the list filters). */
    public function export(Request $request)
    {
        $this->authorizeAccess($request);
        $q = trim((string) $request->input('q', ''));
        $status = $request->input('status', 'all');

        $query = Expense::query()->with(['vendor:id,name', 'account:id,code,name']);
        if ($q !== '') {
            $query->where(fn ($qq) => $qq->where('code', 'like', "%{$q}%")->orWhere('reference_no', 'like', "%{$q}%")
                ->orWhere('description', 'like', "%{$q}%")->orWhereHas('vendor', fn ($v) => $v->where('name', 'like', "%{$q}%")));
        }
        if (in_array($status, ['draft', 'posted', 'void'], true)) { $query->where('status', $status); }

        return \Maatwebsite\Excel\Facades\Excel::download(
            new \App\Exports\V2\StyledQueryExport(
                $query->orderByDesc('id'),
                ['Code', 'Date', 'Reference', 'Vendor', 'Account', 'Description', 'Amount', 'Status'],
                fn ($e) => [$e->code, (string) $e->expense_date, $e->reference_no, $e->vendor?->name, $e->account?->name, $e->description, number_format((float) $e->amount, 3, '.', ''), $e->status],
                'Expenses',
                app()->getLocale() === 'ar',
            ),
            'expenses-'.now()->format('Ymd-His').'.xlsx',
        );
    }

        public function index(Request $request): Response
    {
        $this->authorizeAccess($request);

        $filters = [
            'q' => trim((string) $request->input('q', '')),
            'status' => $request->input('status', 'all'),
        ];

        $query = Expense::query()->with(['vendor:id,name', 'account:id,code,name', 'paymentAccount:id,code,name']);

        if ($filters['q'] !== '') {
            $q = $filters['q'];
            $query->where(fn ($qq) => $qq->where('code', 'like', "%{$q}%")
                ->orWhere('reference_no', 'like', "%{$q}%")
                ->orWhere('description', 'like', "%{$q}%")
                ->orWhereHas('vendor', fn ($v) => $v->where('name', 'like', "%{$q}%")));
        }
        if (in_array($filters['status'], ['draft', 'posted', 'void'], true)) {
            $query->where('status', $filters['status']);
        }

        $page = $query->orderByDesc('id')->paginate(25)->withQueryString();

        return Inertia::render('Expenses/Index', [
            'filters' => $filters,
            'page' => $page,
            'statuses' => ['draft', 'posted', 'void'],
            'counts' => [
                'total' => Expense::query()->count(),
                'draft' => Expense::query()->where('status', 'draft')->count(),
            ],
            'can_edit' => $this->canEdit($request),
        ]);
    }

    /** Vendor / account / branch pickers shared by the create/edit page. */
    protected function pickerData(): array
    {
        return [
            'vendors' => Vendor::query()->where('is_active', true)->orderBy('name')->get(['id', 'name', 'default_account_id'])
                ->map(fn ($v) => ['id' => $v->id, 'name' => $v->name, 'default_account_id' => $v->default_account_id])->all(),
            'expense_accounts' => $this->expenseAccountOptions(),
            'payment_accounts' => $this->paymentAccountOptions(),
            'branches' => $this->accessibleBranches()->all(),
        ];
    }

    /** Dedicated create page (replaces the old modal). */
    public function create(Request $request): Response
    {
        $this->authorizeAccess($request);
        abort_unless((bool) $request->user()->can('create_accounting_expenses'), 403);

        return Inertia::render('Expenses/Form', array_merge($this->pickerData(), [
            'mode' => 'create',
            'expense' => null,
        ]));
    }

    /** Dedicated edit page for a draft (posted / void expenses are immutable). */
    public function edit(Request $request, Expense $expense): Response|RedirectResponse
    {
        $this->authorizeAccess($request);
        abort_unless($this->canEdit($request), 403);
        if ($expense->status !== 'draft') {
            return redirect()->route('v2.accounting.expenses.index')
                ->with('flash', ['type' => 'error', 'message' => 'Only draft expenses can be edited.']);
        }

        return Inertia::render('Expenses/Form', array_merge($this->pickerData(), [
            'mode' => 'edit',
            'expense' => [
                'id' => $expense->id,
                'expense_date' => \Illuminate\Support\Carbon::parse($expense->expense_date)->toDateString(),
                'vendor_id' => $expense->vendor_id,
                'branch_id' => $expense->branch_id,
                'account_id' => $expense->account_id,
                'payment_account_id' => $expense->payment_account_id,
                'amount' => (float) $expense->amount,
                'description' => $expense->description ?? '',
                'reference_no' => $expense->reference_no ?? '',
            ],
        ]));
    }

    public function store(Request $request): RedirectResponse
    {
        $this->authorizeAccess($request);
        if (! $request->user()->can('create_accounting_expenses')) abort(403);
        Expense::create($this->validated($request) + ['status' => 'draft']);
        return redirect()->route('v2.accounting.expenses.index')
            ->with('flash', ['type' => 'success', 'message' => 'Expense recorded.']);
    }

    public function update(Request $request, Expense $expense): RedirectResponse
    {
        $this->authorizeAccess($request);
        if (! $this->canEdit($request)) abort(403);
        if ($expense->status !== 'draft') {
            return back()->with('flash', ['type' => 'error', 'message' => 'Only draft expenses can be edited.']);
        }
        $expense->update($this->validated($request));
        return redirect()->route('v2.accounting.expenses.index')
            ->with('flash', ['type' => 'success', 'message' => 'Expense updated.']);
    }

    public function post(Request $request, Expense $expense): RedirectResponse
    {
        $this->authorizeAccess($request);
        if (! $this->canEdit($request)) abort(403);
        try {
            $expense->post((int) $request->user()->id);
            if ($expense->refresh()->status !== 'posted') {
                return back()->with('flash', ['type' => 'error', 'message' => 'Posting failed — check that the required accounts are configured.']);
            }
        } catch (\Throwable $e) {
            return back()->with('flash', ['type' => 'error', 'message' => $e->getMessage()]);
        }
        return back()->with('flash', ['type' => 'success', 'message' => 'Expense posted to the ledger.']);
    }

    public function void(Request $request, Expense $expense): RedirectResponse
    {
        $this->authorizeAccess($request);
        if (! $this->canEdit($request)) abort(403);
        try {
            $expense->void((int) $request->user()->id);
        } catch (\Throwable $e) {
            return back()->with('flash', ['type' => 'error', 'message' => $e->getMessage()]);
        }
        return back()->with('flash', ['type' => 'success', 'message' => 'Expense voided.']);
    }

    public function destroy(Request $request, Expense $expense): RedirectResponse
    {
        $this->authorizeAccess($request);
        if (! $request->user()->can('delete_accounting_expenses')) abort(403);
        if ($expense->status === 'posted') {
            return back()->with('flash', ['type' => 'error', 'message' => 'Void the expense before deleting it.']);
        }
        $expense->delete();
        return back()->with('flash', ['type' => 'success', 'message' => 'Expense deleted.']);
    }

    protected function validated(Request $request): array
    {
        return $request->validate([
            'expense_date' => ['required', 'date'],
            'vendor_id' => ['nullable', 'integer', Rule::exists('vendors', 'id')],
            'branch_id' => ['nullable', 'integer', 'exists:branches,id'],
            'account_id' => ['required', 'integer', Rule::exists('chart_of_accounts', 'id')],
            'payment_account_id' => ['nullable', 'integer', Rule::exists('chart_of_accounts', 'id')],
            'amount' => ['required', 'numeric', 'min:0.001'],
            'description' => ['nullable', 'string', 'max:500'],
            'reference_no' => ['nullable', 'string', 'max:191'],
        ]);
    }

    protected function expenseAccountOptions(): array
    {
        return Account::query()
            ->whereIn('type', [Account::TYPE_EXPENSE, Account::TYPE_COGS])
            ->where('is_active', true)->orderBy('code')
            ->get(['id', 'code', 'name'])
            ->map(fn ($a) => ['id' => $a->id, 'label' => "{$a->code} — {$a->name}"])->all();
    }

    protected function paymentAccountOptions(): array
    {
        return Account::query()
            ->where('type', Account::TYPE_ASSET)->where('is_active', true)
            ->where(function ($q) {
                $q->whereIn('code', ['1110', '1120', '1130'])
                    ->orWhere('code', 'like', '1110-%')->orWhere('code', 'like', '1120-%');
            })
            ->orderBy('code')->get(['id', 'code', 'name'])
            ->map(fn ($a) => ['id' => $a->id, 'label' => "{$a->code} — {$a->name}"])->all();
    }
}
