<?php

namespace App\Http\Controllers\V2;

use App\Http\Controllers\Controller;
use App\Models\FollowUpPlan;
use Illuminate\Http\Request;
use Inertia\Inertia;
use Inertia\Response;

/**
 * Follow-up Plans — v2 replacement for the Filament FollowUpPlanResource.
 *
 * Read-only. Plans are generated by the Visit save hook; this is the oversight
 * list (who is due back, was a booking auto-created, which visit triggered it).
 * Branch scoping is automatic via the model's BelongsToBranchScope.
 */
class FollowUpPlansController extends Controller
{
    protected function authorizeView(Request $request): void
    {
        if (! $request->user() || ! $request->user()->can('view_any_follow_up_plans')) {
            abort(403, 'Not authorized to view follow-up plans.');
        }
    }

    /** Styled .xlsx export (mirrors the list filters). */
    public function export(Request $request)
    {
        $this->authorizeView($request);
        $q = trim((string) $request->input('q', ''));
        $booking = $request->input('booking', 'all');
        $from = $request->input('from');
        $until = $request->input('until');
        $query = FollowUpPlan::query()->with(['patient:id,name,phone', 'doctor:id,name', 'sourceVisit:id,booking_code', 'booking:id,booking_code']);
        if ($q !== '') { $query->whereHas('patient', fn ($p) => $p->where('name', 'like', "%{$q}%")->orWhere('phone', 'like', "%{$q}%")); }
        if ($booking === 'with') { $query->whereNotNull('booking_id'); } elseif ($booking === 'without') { $query->whereNull('booking_id'); }
        if ($from) { $query->whereDate('suggested_at', '>=', $from); }
        if ($until) { $query->whereDate('suggested_at', '<=', $until); }
        return \Maatwebsite\Excel\Facades\Excel::download(
            new \App\Exports\V2\StyledQueryExport(
                $query->orderByDesc('id'),
                ['ID', 'Patient', 'Phone', 'Doctor', 'Source visit', 'Booking', 'Auto-create booking', 'Suggested at'],
                fn ($r) => [$r->id, $r->patient?->name, $r->patient?->phone, $r->doctor?->name, $r->sourceVisit?->booking_code, $r->booking?->booking_code, $r->auto_create_booking ? 'Yes' : 'No', (string) $r->suggested_at],
                'Follow-up Plans',
                app()->getLocale() === 'ar',
            ),
            'follow-up-plans-'.now()->format('Ymd-His').'.xlsx',
        );
    }

        public function index(Request $request): Response
    {
        $this->authorizeView($request);

        $filters = [
            'q' => trim((string) $request->input('q', '')),
            'booking' => $request->input('booking', 'all'),
            'from' => $request->input('from'),
            'until' => $request->input('until'),
        ];

        $query = FollowUpPlan::query()
            ->with(['patient:id,name,phone', 'doctor:id,name', 'sourceVisit:id,booking_code', 'booking:id,booking_code']);

        if ($filters['q'] !== '') {
            $q = $filters['q'];
            $query->whereHas('patient', fn ($p) => $p->where('name', 'like', "%{$q}%")->orWhere('phone', 'like', "%{$q}%"));
        }
        if ($filters['booking'] === 'with') {
            $query->whereNotNull('booking_id');
        } elseif ($filters['booking'] === 'without') {
            $query->whereNull('booking_id');
        }
        if ($filters['from']) {
            $query->whereDate('suggested_at', '>=', $filters['from']);
        }
        if ($filters['until']) {
            $query->whereDate('suggested_at', '<=', $filters['until']);
        }

        $page = $query->orderByDesc('id')->paginate(25)->withQueryString();
        $page->getCollection()->transform(fn (FollowUpPlan $r) => [
            'id' => $r->id,
            'suggested_at' => optional($r->suggested_at)->format('Y-m-d h:i A'),
            'patient' => $r->patient?->name,
            'patient_phone' => $r->patient?->phone,
            'doctor' => $r->doctor?->name,
            'auto_create_booking' => (bool) $r->auto_create_booking,
            'source_visit_id' => $r->source_visit_id,
            'source_visit_code' => $r->sourceVisit?->booking_code,
            'booking_code' => $r->booking?->booking_code,
            'status' => $r->status,
        ]);

        return Inertia::render('FollowUpPlans/Index', [
            'filters' => $filters,
            'page' => $page,
            'counts' => [
                'total' => FollowUpPlan::query()->count(),
                'with_booking' => FollowUpPlan::query()->whereNotNull('booking_id')->count(),
                'without_booking' => FollowUpPlan::query()->whereNull('booking_id')->count(),
            ],
        ]);
    }
}
